// this file was generated by serverless-auto-swagger
module.exports = {
  swagger: "2.0",
  info: {
    title: "AWS Course EPAM - Online Shop",
    version: "1",
  },
  paths: {
    "/products/{productId}": {
      get: {
        summary: "getProductById",
        description: "",
        operationId: "getProductById.get.products/{productId}",
        consumes: ["application/json"],
        produces: ["application/json"],
        parameters: [
          {
            name: "productId",
            in: "path",
            required: true,
            type: "string",
          },
        ],
        responses: {
          200: {
            description: "Get Product Success",
            schema: {
              $ref: "#/definitions/Product",
            },
          },
          400: {
            description: "Product not found",
          },
          500: {
            description: "Internal Server Error",
          },
        },
      },
    },
    "/products": {
      get: {
        summary: "getAllProducts",
        description: "",
        operationId: "getAllProducts.get.products",
        consumes: ["application/json"],
        produces: ["application/json"],
        parameters: [],
        responses: {
          200: {
            description: "Get Products Success",
            schema: {
              $ref: "#/definitions/Products",
            },
          },
          400: {
            description: "Products not found",
          },
          500: {
            description: "Internal Server Error",
          },
        },
      },
    },
  },
  definitions: {
    Product: {
      properties: {
        id: {
          title: "Product.id",
          type: "string",
        },
        title: {
          title: "Product.title",
          type: "string",
        },
        description: {
          title: "Product.description",
          type: "string",
        },
        price: {
          title: "Product.price",
          type: "number",
        },
        count: {
          title: "Product.count",
          type: "number",
        },
      },
      required: ["id", "title", "description", "price", "count"],
      additionalProperties: false,
      title: "Product",
      type: "object",
    },
    Products: {
      items: {
        $ref: "#/definitions/Product",
        title: "Products.[]",
      },
      title: "Products.[]",
      type: "array",
    },
  },
  securityDefinitions: {},
  host: "lfh6re2wfg.execute-api.eu-west-1.amazonaws.com/dev",
};
